dbt-beers:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: DATAFOLDROLE
      database: DATAFOLD_DEMO
      warehouse: COMPUTE_WH
      schema: BEER_ANALYTICS
      threads: 1

databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: beers
      host: "{{ env_var('DATABRICKS_HOST') | as_text }}"
      http_path: "{{ env_var('DATABRICKS_PATH') | as_text }}"
      token: "{{ env_var('DATABRICKS_TOKEN') | as_text }}"

production:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: DATAFOLDROLE
      database: INTEGRATION
      warehouse: INTEGRATION
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | as_text }}"
      threads: 5
