redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      host: 52.43.146.141
      user: fokko
      password: "{{ env_var('REDSHIFT_PASSWORD') | as_text }}"
      port: 5439
      dbname: dev
      schema: "{{ env_var('REDSHIFT_SCHEMA') | as_text }}"
      threads: 2
