snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: demo_beers
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: PUBLIC
      database: INTEGRATION
      warehouse: INTEGRATION
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | as_text }}"
      threads: 5
